// packages/app-nav-vue/src/App.vue
<script setup lang="ts">
import { IconBrandVue } from '@tabler/icons-vue'
import './assets/base.css'
import './assets/main.css'
</script>

<template>
  <div class="nav--container">
    <div class="watermark">
      <IconBrandVue size="120" color="#07070a" />
      <p class="watermark--title">Vue Sidebar</p>
    </div>
  </div>
</template>

<style scoped>
.nav--container {
  position: relative;
  width: 100%;
  height: 100%;
}

.watermark {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  color: #07070a;
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.watermark--title {
  font-size: 28px;
  font-weight: 600;
}

header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>

// packages/app-footer-svelte/src/App.svelte
<script>

  import { IconBrandSvelte } from '@tabler/icons-svelte';
  export let name;
</script>

<section>
  <IconBrandSvelte size="36" />
  <p>Svelte Footer</p>
</section>

<style>
  section {
    background: #4A525A;
    color: white;
    display: flex;
    height: 52px;
    padding: 0 8px;
    justify-content: center;
    align-items: center;
    gap: 8px;
    font-size: 1.5rem;
    font-weight: 600;
  }
</style>
